# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenAPIClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenAPIClient

end

target 'PetStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PetStore

  target 'PetStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PetStoreUITests' do
    # Pods for testing
  end

end
